### ISSUE TITLE
loadFactor parameter overlooked

### ISSUE THREAD

**Issue by miroslavp** [Wsm2110/Faster.Map#11]
I noticed that you amended the code to set the loadfactor to the field
https://github.com/Wsm2110/Faster.Map/blob/1de97cb368aad2cdbc1acb9f3f10edbf231588f0/src/DenseMapSIMD.cs#L180-L183

however this line still uses the parameter and not the field

https://github.com/Wsm2110/Faster.Map/blob/1de97cb368aad2cdbc1acb9f3f10edbf231588f0/src/DenseMapSIMD.cs#L194

Thanks for getting time to fix it

**Comment by Wsm2110** [comment]
silly mistake, fixed
