### ISSUE TITLE
Question: Is it safe to make jump_distances static?

### ISSUE THREAD

**Issue by miroslavp** [Wsm2110/Faster.Map#12]
Hi,
I noticed that jump_distances is read-only and never modified. Is it safe to make it static, so it is not allocated per instance?

https://github.com/Wsm2110/Faster.Map/blob/99a11197c7bf46fc975f44c9aceb91da07689373/src/DenseMapSIMD.cs#L131-L141

**Comment by Wsm2110** [comment]
fixed
