### ISSUE TITLE
Possible bug in DenseMapSIMD.Copy(DenseMapSIMD<TKey, TValue> denseMap)

### ISSUE THREAD

**Issue by miroslavp** [Wsm2110/Faster.Map#13]
In the Copy method below:
https://github.com/Wsm2110/Faster.Map/blob/99a11197c7bf46fc975f44c9aceb91da07689373/src/DenseMapSIMD.cs#L608-L620

shouldn't this if statement check for **denseMap._metadata[i] < 0** rather than  **_metadata[i] < 0** as it is now?
https://github.com/Wsm2110/Faster.Map/blob/99a11197c7bf46fc975f44c9aceb91da07689373/src/DenseMapSIMD.cs#L612-L615

**Comment by Wsm2110** [comment]
Fixed
