### ISSUE TITLE
Question about DenseMapSIMD.Emplace(TKey key, TValue value)

### ISSUE THREAD

**Issue by miroslavp** [Wsm2110/Faster.Map#14]
According to your documentation, Emplace method should return false if the key already exists
https://github.com/Wsm2110/Faster.Map/blob/7c076563c31db5aedb3d832d3b9362ca77dab01d/src/DenseMapSIMD.cs#L211-L218
Don't we check for the key existence here?
https://github.com/Wsm2110/Faster.Map/blob/7c076563c31db5aedb3d832d3b9362ca77dab01d/src/DenseMapSIMD.cs#L255-L258

**Comment by Wsm2110** [comment]
should return false indeed 👍
