### ISSUE TITLE
Suggestion about Resize()

### ISSUE THREAD

**Issue by miroslavp** [Wsm2110/Faster.Map#15]
I have a suggestion for the code bellow in the Resize() method:
https://github.com/Wsm2110/Faster.Map/blob/883c9fe55030bb0be7cd90e166ee7d2c6e931924/src/DenseMapSIMD.cs#L758-L762
It can be simplified to
```cs
var oldEntries = _entries.Clone();
var oldMetadata = _metadata.Clone();
```
It looks simpler and is slightly faster. I tried it with array of 1_000_000 ints and it was about 30% faster. 
Both the Array.Copy and Array.Clone make shallow copy.

**Comment by Wsm2110** [comment]
Thnx, didn`t know that :)
