### ISSUE TITLE
Bug in the last commit

### ISSUE THREAD

**Issue by miroslavp** [Wsm2110/Faster.Map#21]
I've tested your last commit and it returns wrong results for Get()

Please note that the original code was calling LoadUnsafe with two parameters -> source (`ref _metadata[index]`) and offset (`jumpDistance`)
```csharp
var right = Vector128.LoadUnsafe(ref _metadata[index], jumpDistance);
```
In the new code we call it with one parameter -> only the source (`ref GetArrayValRef(_metadata, index)`)
```csharp
var right = Vector128.LoadUnsafe(ref GetArrayValRef(_metadata, index));
```
 which is the same as 
 ```csharp
var right = Vector128.LoadUnsafe(ref _metadata[index]);
```
but without the bounds check.

This is because we add the offset to the index variable later on in the code
```csharp               
//Calculate jumpDistance
index += GetArrayVal(jump_distances, jumpDistanceIndex);
```
However it is **important to subtract the previous jumpDistance**, before adding the new one, as it was in my code. 
```csharp
  //subtract last jump distance from the index
  index -= jumpDistance;

  //set the new jump distance
  jumpDistance = GetArrayVal(jump_distances, distanceIndex);

  //recalculate index, taking into account the new jump distance
  index += jumpDistance;
```
otherwise on the next loop iteration the code would look something like this 
**(this is pseudo code)**
```csharp
var right = Vector128.LoadUnsafe(ref _metadata[originalIndex +  oldJumpDistance + newJumpDistance]);
```
And this is not what we want. We want
```csharp
var right = Vector128.LoadUnsafe(ref _metadata[originalIndex + newJumpDistance]);
```
---------------------------
Also can you please explain this part
https://github.com/Wsm2110/Faster.Map/blob/cbd10bd253185fa7e605c892f9c6bf0538927a6b/src/DenseMapSIMD.cs#L385-L390
I thought it should be just
```csharp
 if (index > _length) 
 {     
     return false;
 } 
```
I read it as "If index > length, start all over again" which looks like endless loop to me

**Comment by Wsm2110** [comment]
Pretty sure there is no bug, every unittest succeeded. Ill explain when i have some free time.

**Comment by miroslavp** [comment]
Run the GetBenchmark and count how many `false` values returns `_denseMapSIMD.Get(key, out var result);` in the loop. It should be 100_000, right? It returns 109_735 for me

**Comment by Wsm2110** [comment]
Ill add some comments in an our or two.

**Comment by Wsm2110** [comment]
Added some new code mate.

**Comment by miroslavp** [comment]
I've read your comments in the code. Not that I understood them completely :blush: , but it definitely makes more sense now :smiley: . I intend to spend some time to learn more about this data structure. If you have any sources of information on the topic and want to share, it would be much appreciated.

You can go ahead and close this issue.

**Comment by Wsm2110** [comment]
Watch CppCon 2017: Matt Kulukundis “Designing a Fast, Efficient,
Cache-friendly Hash Table, Step by Step”' op YouTube

And he has a follow up which was released in 2019

You could try and search for Swisstable

Have fun :)

Op do 9 mrt. 2023 20:30 schreef Miroslav Parvanov ***@***.***

**Comment by miroslavp** [comment]
Hi again @Wsm2110 
There's this thing that bothers me a lot and gives me anxiety (not joking). Can you please **confirm** that the following behavior after the last code changes is intentional. I really don't want some bugs to slip into the code. I have a gut feeling that this was made by mistake. The tests don't catch it as the new behavior is replicated in all methods.
The `LoadUnsafe` in the new impementation loads the groups from different offsets. As I said in my first comment, this is because of the new index calculation (+= operator)
Here's what the code looks like on every loop iteration

**old version**
```csharp
//first loop iteration
var right = Vector128.LoadUnsafe(ref _metadata[hashcode * GoldenRatio >> _shift], 0);
//second loop iteration
var right = Vector128.LoadUnsafe(ref _metadata[hashcode * GoldenRatio >> _shift], 32);
//third loop iteration
var right = Vector128.LoadUnsafe(ref _metadata[hashcode * GoldenRatio >> _shift], 80);
//forth loop iteration
var right = Vector128.LoadUnsafe(ref _metadata[hashcode * GoldenRatio >> _shift], 144);
//fifth loop iteration
var right = Vector128.LoadUnsafe(ref _metadata[hashcode * GoldenRatio >> _shift], 240);
//sixth loop iteration
var right = Vector128.LoadUnsafe(ref _metadata[hashcode * GoldenRatio >> _shift], 320);
//seventh loop iteration
var right = Vector128.LoadUnsafe(ref _metadata[hashcode * GoldenRatio >> _shift], 432);
//...and so on
```

**new version**
```csharp
//first loop iteration
var right = Vector128.LoadUnsafe(ref GetArrayValRef(_metadata, hashcode * GoldenRatio >> _shift));
//second loop iteration
var right = Vector128.LoadUnsafe(ref GetArrayValRef(_metadata, hashcode * GoldenRatio >> _shift + 32));
//third loop iteration
var right = Vector128.LoadUnsafe(ref GetArrayValRef(_metadata, hashcode * GoldenRatio >> _shift + 112));
//forth loop iteration
var right = Vector128.LoadUnsafe(ref GetArrayValRef(_metadata, hashcode * GoldenRatio >> _shift + 256));
//fifth loop iteration
var right = Vector128.LoadUnsafe(ref GetArrayValRef(_metadata, hashcode * GoldenRatio >> _shift + 496));
//sixth loop iteration
var right = Vector128.LoadUnsafe(ref GetArrayValRef(_metadata, hashcode * GoldenRatio >> _shift + 816));
//seventh loop iteration
var right = Vector128.LoadUnsafe(ref GetArrayValRef(_metadata, hashcode * GoldenRatio >> _shift + 1248));
//...and so on
```

As you can see, the offset grows a lot faster in the new version. I thought that those jump distances constants are important part of the algorithm. Is this accumulation intentional in the new code. Don't want to be pain in the a$$, just want everything to be alright in the code.

**Comment by Wsm2110** [comment]
Noticed this as well. Should be fixed now.

Just wanted to thank you for all your time you put in this repository. Much
appreciated.

Op vr 10 mrt. 2023 11:23 schreef Miroslav Parvanov ***@***.***
