### ISSUE TITLE
Potential optimization for big structs

### ISSUE THREAD

**Issue by miroslavp** [Wsm2110/Faster.Map#22]
Maybe we should consider changing this line inside `Emplace()` 
https://github.com/Wsm2110/Faster.Map/blob/7e1fb1ee10443cb520ce3e2a1108be0990de304a/src/DenseMapSIMD.cs#L244
to 
```csharp
 ref readonly var entry = ref GetArrayValRef(_entries, indexAndOffset); 
```
and this line inside `Get()`
https://github.com/Wsm2110/Faster.Map/blob/7e1fb1ee10443cb520ce3e2a1108be0990de304a/src/DenseMapSIMD.cs#L351
to
```csharp
ref readonly var entry = ref GetArrayValRef(_entries, index + Unsafe.As<int, uint>(ref offset)); 
```
This way we can avoid copying large entries (when we have large TKey and/or TValue) from the _entries array. What do you think?

**Comment by Wsm2110** [comment]
fixed
