### ISSUE TITLE
DenseMapSIMD Throws IndexOutOfRangeException inside Contains

### ISSUE THREAD

**Issue by NightlyRevenger** [Wsm2110/Faster.Map#28]
DenseMapSIMD Throws IndexOutOfRangeException inside Contains when small length was passed into constructor.

Minimum working example:
```
var fmap = new DenseMapSIMD<long, long>(1);
fmap.Emplace(0L, 0L);

var r = fmap.Contains(1);
```
The piece of code above throws IndexOutOfRangeException inside GetArrayEntryRef
Most likely the reason is `length` instead of  `_length` here:

https://github.com/Wsm2110/Faster.Map/blob/27ede7ac7717dfc54c9d81e99e76f5e859ba69d7/src/DenseMapSIMD.cs#L174-L177

**Comment by Wsm2110** [comment]
Fixed
