### ISSUE TITLE
More methods

### ISSUE THREAD

**Issue by frankhommers** [Wsm2110/Faster.Map#3]
These changes would be a great addition:

* ContainsKey - Should check if a key exists
* GetOrThrow - Should throw if the requested key does not exist
* Indexers 
  * var value = VarName[key] (Also should throw if the requested key does not exists)
  * VarName[key] = value (should call emplace)

**Comment by Wsm2110** [comment]
#ContainsKey - you could use Emplace() which returns false if the key is used
#GetOrThrow - not really sure why you would want to throw, i always hated the fact that dictionaries throw while the key is not found. It returns a default value in which you can decide whether you want to throw or not.
#Indexors - will do :)

**Comment by frankhommers** [comment]
* GetOrThrow: I sometimes have keys with values as their defaults, so I can't tell the difference.
* ContainsKey: I do not always want to emplace.

Nice work BTW.

**Comment by Wsm2110** [comment]
Thnx, ik kijk er woensdag even naar ;)

Op vr 12 nov. 2021 14:58 schreef Frank Hommers ***@***.***>:

**Comment by Wsm2110** [comment]
*Get now returns a bool if the key exists which should be a proper replacement for ContainsKey
*Added indexers which throw if the key hasnt been found
