### ISSUE TITLE
Missing Resize() in GetOrAdd

### ISSUE THREAD

**Issue by lakecherry** [Wsm2110/Faster.Map#30]
Method gets caught in endless while (true) loop ... adding Resize() similar to Emplace etc. solves it ...

```
[TestMethod]
public void AssertGetOrAddMultipleValues()
{
    //assign
    var map = new DenseMap<int, int>();

    for (int i = 0; i < 20; i++)
    {
        map.GetOrAdd (i);                                   // caught in endless while (true) loop at index 18
    }
}
```

**Comment by Wsm2110** [comment]
Will look into it

Op do 16 nov. 2023 09:20 schreef lakecherry ***@***.***>:

**Comment by Wsm2110** [comment]
Fixed :>

**Comment by lakecherry** [comment]
Thanks ... really like this project!

**Comment by Wsm2110** [comment]
I should probably be thanking you for spending time finding bugs.
Appreciate it

Op za 18 nov. 2023 09:42 schreef lakecherry ***@***.***>:

**Comment by lakecherry** [comment]
Had the situation of applying some operation to all dictionary values (struct), so i added this enumerator to efficiently ref return all values ... just in case you find it helpful and want to add to your project (.NET 8 required) ...

```
		#region Enumerator

		public Enumerator GetEnumerator() => new (_metadata, _entries);

		public ref struct Enumerator (sbyte[] metadata, Entry[] entries)
		{
			public bool MoveNext()
			{
				do
				{
					this.pMetadataOffset = ref Unsafe.Subtract (ref this.pMetadataOffset, 1);

					if (Unsafe.IsAddressLessThan (ref this.pMetadataOffset, ref this.pMetadata))
						return false;

				} while (this.pMetadataOffset < 0);

				return true;
			}

			public ref TValue Current => ref Unsafe.Add (ref this.pEntries, Unsafe.ByteOffset (ref this.pMetadata, ref this.pMetadataOffset)).Value;

			//
			ref sbyte pMetadataOffset = ref Unsafe.Add (ref MemoryMarshal.GetArrayDataReference (metadata), metadata.Length),
			          pMetadata = ref MemoryMarshal.GetArrayDataReference (metadata);

			ref Entry pEntries = ref MemoryMarshal.GetArrayDataReference (entries);
		}

		#endregion
```

**Comment by Wsm2110** [comment]
Add a pull request :)

Op zo 7 apr 2024 12:55 schreef lakecherry ***@***.***>:

**Comment by lakecherry** [comment]
"Pull request creation failed. Validation failed: must be a collaborator" ... i'm probably doing it wrong ;)

**Comment by Wsm2110** [comment]
Collaborators only mode is disabled, zo im not really sure what you're
doing.

I usually create a fork, Add some code and push. After you can create a
pull request on GitHub.

Let me know if it works

Op zo 7 apr 2024 19:49 schreef lakecherry ***@***.***>:
