### ISSUE TITLE
Question about the new Rehash method

### ISSUE THREAD

**Issue by miroslavp** [Wsm2110/Faster.Map#38]
Hi Wiljan, 
I saw that you have added a new Rehash method. Is it critical for the DenseMap to work correctly or is it just for optimization purposes (better performance)?

Thank you for taking time to fix the issue.

**Comment by Wsm2110** [comment]
This rehash helps maintain performance by preventing excessive tombstone accumulation, which could lead to longer probe chains and slower lookups. 

By cleaning up tombstones, we ensure that probe chains remain short and that the table remains efficient.

**Comment by miroslavp** [comment]
Ok, thanks
