### ISSUE TITLE
Fatal error. System.AccessViolationException: Attempted to read or write protected memory.

### ISSUE THREAD

**Issue by check4game** [Wsm2110/Faster.Map#40]
Hi

https://github.com/Wsm2110/Faster.Map/blob/a7fb8fff834f62cdabdd1072a9559330878a6dce/src/RobinHoodMap.cs#L242-L245

code to reproduce

```
var robinhoodMap = new RobinhoodMap<uint, uint>(12_000_000);

var rnd0 = new Random(3);

for (int j = 0; j < 50_000_000; j++)
{
    robinhoodMap.Emplace((uint)rnd0.Next(), 0);
    if (robinhoodMap.Count == 7_000_000) break;
}

var rndInts = robinhoodMap.Keys.ToArray();

RobinhoodMap<uint, uint> map = new(1024 * 1024);

for (uint i = 0; i < rndInts.Length; i++)
{
    var v = rndInts[i];

    if (i == 4135)
    {
        map.Emplace(v, v);
    }
    map.Emplace(v, v);
}
```

Do I understand correctly that RobinhoodMap is the first version of DenseMap? and there are no plans to find a solution to the problem?

**Comment by Wsm2110** [comment]
Hi,

RobinhoodMap was the first hashmap I developed. However, the internals of DenseMap are entirely different from RobinhoodMap, making them difficult to compare directly.

Without sounding presumptuous, I believe I may have resolved your issue.

**Comment by check4game** [comment]
Hi,

> Without sounding presumptuous, I believe I may have solved your issue.

https://github.com/Wsm2110/Faster.Map/blob/5e9b947897ecb3651eef0694cd1727f743c06724/src/RobinHoodMap.cs#L83-L86

This is not a solution for issue, but hiding it.

it is enough to replace one line in the test

https://github.com/Wsm2110/Faster.Map/blob/5e9b947897ecb3651eef0694cd1727f743c06724/unittests/Faster.Map.RobinhoodMap.Tests/RobinhoodEmplaceUnitTests.cs#L75-L77

`var rndInts = robinhoodMap.Keys.Reverse().ToArray();`

It doesn’t matter how the data set was obtained, what matters is that such a set is possible!

It’s obvious that the problem is in the procedure of adding a new element to the map

**Comment by Wsm2110** [comment]
fixed and closed
