### ISSUE TITLE
Throws `IndexOutOfRange` on large amount of items (with the same hash?) inserted

### ISSUE THREAD

**Issue by lynzrand** [Wsm2110/Faster.Map#7]
Minimum working example:

```csharp
var map = new MultiMap<int, int>();
for (int i = 0; i < 1000; i++)
{
    // Console.WriteLine(i);
    map.Emplace(2, i); 			// line 86
}
```

The piece of code above throws the following error on my machine on the 914th iteration:

```
Error message:
   System.IndexOutOfRangeException : Index was outside the bounds of the array.
Stacktrace:
     at <snip>.Tests.MultimapTest() in <snip>\Tests.cs:line 86
```

Similar problems also happen if you replace the `2` with other numbers or `new object()`, etc.

---

System information:

.NET 6.0.400  
Target Framework: net6.0 (bin), netstandard2.0 (lib)  
System: Windows 11 22H2 x64

**Comment by lynzrand** [comment]
My bad, didn't see the "max. 127 items with the same key can be inserted"

**Comment by Wsm2110** [comment]
> 

Ill add a new version in a couple of days removing the 127 boundary
