### ISSUE TITLE
Possible missing field reintialization

### ISSUE THREAD

**Issue by miroslavp** [Wsm2110/Faster.Map#8]
I spotted something suspicious while looking at the code. 
https://github.com/Wsm2110/Faster.Map/blob/80e97b7d082cd696260acd362bac5aade6c98028/src/DenseMapSIMD.cs#L175-L180
Don't we need to reinitialize the _loadfactor field inside the if block with 0.9 as well?

**Comment by Wsm2110** [comment]
Thnx mate, ill fix it later

**Comment by Wsm2110** [comment]
fixed
